@startuml
left to right direction
actor Usuario as user

rectangle "Frontend (Vue)" {
  component "Vista (V)\nComponentes Vue" as vue
}

rectangle "Backend (Spring Boot)" {
  component "Spring Security\n(CORS + JWT + Roles)" as security
  component "Controller" as controller
  component "Service" as service
  component "Repository" as repository
  component "Entity" as entity
}

database "Data base (PostgreSQL)" as db

' Flujo de interacción
user --> vue : Interacción (login, CRUD)
vue --> security : Request HTTP (JWT + Headers)
security --> controller : Petición autorizada
controller --> service : Lógica de negocio
service --> repository : Operaciones de datos
repository --> entity : Mapeo ORM
repository --> db : Query SQL

' Respuesta hacia el usuario
db --> repository
repository --> service
service --> controller
controller --> vue : Response JSON
vue --> user : Renderiza vista
@enduml