CREATE TABLE "inventory_product_stocks" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "product_id" uuid UNIQUE NOT NULL,
    "quantity" int NOT NULL,
    "update_at" timestamp DEFAULT (now())
);