spring:
  application:
    name: e-commerce
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}?&ssl=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: validate
      show-sql: true

application:
  jwt:
    secret: ${JWT_SECRET_KEY}
    expiration: ${JWT_EXPIRATION_MILLISECOND}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: ${CORS_ALLOWED_METHODS}
  api:
    path:
      prefix: ${API_PREFIX}

# swagger-ui custom path
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs
    version: 1.0


cloudinary:
  cloud:
    name: ${CLOUDINARY_CLOUD_NAME}
  api:
    key: ${CLOUDINARY_API_KEY}
    secret: ${CLOUDINARY_API_SECRET}