CREATE TABLE "sales_order_items" (
     "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     "order_id" uuid NOT NULL,
     "product_id" uuid NOT NULL,
     "quantity" int NOT NULL,
     "price" numeric(10,2) NOT NULL
);